hellomake: eventpool.o main.o
	gcc -g -Wall -fomit-frame-pointer -Wall -o eventpool eventpool.o main.o -luv

eventpool.o: eventpool.c
	gcc -g -Wall -fomit-frame-pointer -c eventpool.c

main.o: main.c
	gcc -g -Wall -fomit-frame-pointer -c main.c