name: CI

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:2020-5-20
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Build android
        run: |
          ./gradlew assembleDebug

